### PR TITLE
Feature/buy me a beer

### PR DESCRIPTION
**Pull request by trenslow**
@lincolnpires i added the buy me a coffee/beer logo, but i cant figure out how to make it the same color as the other ones at the bottom. maybe you have an idea?

### CODE REVIEW

**Comment by lincolnpires** [comment]
Yeah, I took a quick look as well and didn't get what is wrong at first, but now I see.  
But to be honest, I haven't noticed that the icons there are white instead of greenish and that's not intentional. It may be something from BS.

Anyway, 2 things:
1. I think we should go for the uManic purple now that we have it 👍🏾 
2. I inspected them and noticed why the F they are white, there's this "text-light" in the class that forces them to be whited-out. I guess it was there with the BS Studio when I first created it 😅

So, I vote for a `Root.css` with the following:
```css
:root {
  --umanic-purple: #7301ab;
  --bs-primary: #7301ab;
  --bs-secondary: #6c757d;
  --bs-primary-rgb: 115, 1, 171;
  --bs-secondary-rgb: 108, 117, 125;
}

a {
  color: var(--umanic-purple);
}
```

What ya think?

**Comment by lincolnpires** [comment]
Screenshot from in-browser:

image


We need to see what color to go `hovered` as well though 😁

**Comment by trenslow** [comment]
@lincolnpires i dont mind about the .css. Tbh im just learning this html/css stuff as i go; its all new to me.

Im not so convinced about using the purple color, as it doesnt pop out to me as 'click here', like the old green color did

**Comment by trenslow** [comment]
@lincolnpires i made all the links the original green color you had to use as a base in case nothing else looks good :D

**Comment by trenslow** [comment]
@lincolnpires actually, this original branch was meant to get the buy me a coffee link working, which it is. i would say if we're gonna work on the color scheme, we should open a new branch. i will go ahead and merge this one

**Pull request merged**
